export const ZONES_CORDOBA = [
  'Alberdi',
  'Alta Córdoba',
  'Alta Gracia',
  'Alto Verde',
  'Altos del Chateau',
  'Anisacate',
  'Argüello',
  'Ascochinga',
  'Ayacucho',
  'Bajo Palermo',
  'Bella Vista',
  'Bell Ville',
  'Bouwer',
  'Cañuelas Country',
  'Capilla del Monte',
  'Centro',
  'Cerro de las Rosas',
  'Chacras de la Villa',
  'Chateau Carreras',
  'Cofico',
  'Colinas de Vélez Sársfield',
  'Colonia Caroya',
  'Comarca',
  'Cosquín',
  'Country Club Jockey',
  'Crisol Norte',
  'Crisol Sur',
  'Cruz del Eje',
  'El Bosque',
  'El Prado',
  'Empalme',
  'Fontanas del Sur',
  'General Paz',
  'Granja de Funes',
  'Güemes',
  'Hermitage',
  'Hipódromo',
  'Jardín',
  'Jesús María',
  'Juniors',
  'La Calera',
  'La Carolina',
  'La Cumbre',
  'La Cumbrecita',
  'La Falda',
  'La Luisita',
  'La Morada',
  'La Reserva',
  'Laguna Larga',
  'Lomas de Villa Allende',
  'Los Árboles',
  'Los Boulevares',
  'Los Carolinos',
  'Los Cielos',
  'Los Naranjos',
  'Los Pinos',
  'Los Plátanos',
  'Los Reartes',
  'Los Sueños',
  'Malagueño',
  'Manantiales',
  'Manantiales I',
  'Manantiales II',
  'Mansos del Sur',
  'Marcos Juárez',
  'Mendiolaza',
  'Nueva Córdoba',
  'Nueva Italia',
  'Observatorio',
  'Oncativo',
  'Parque Montecristo',
  'Parque Vélez Sársfield',
  'Pilar',
  'Poeta Lugones',
  'Pueyrredón',
  'Quintas de San Isidro',
  'Residencial América',
  'Residencial San Carlos',
  'Río Ceballos',
  'Río Cuarto',
  'Río Tercero',
  'Salsipuedes',
  'San Antonio',
  'San Fernando',
  'San Francisco',
  'San Martín',
  'San Vicente',
  'Santa Rosa de Calamuchita',
  'Santina Norte',
  'Sierra Nueva',
  'Sinsacate',
  'Tablada Park',
  'Talar',
  'Talleres',
  'Toledo',
  'Tropezon',
  'Unquillo',
  'Urca',
  'Valle del Sol',
  'Valle Escondido',
  'Valle Hermoso',
  'Villa Allende',
  'Villa Belgrano',
  'Villa Cabrera',
  'Villa Carlos Paz',
  'Villa del Dique',
  'Villa del Parque',
  'Villa El Libertador',
  'Villa General Belgrano',
  'Villa Giardino',
  'Villa María',
  'Villa Páez',
  'Villa Revol',
  'Villa Rivera Indarte',
  'Villa Warcalde',
  'Villasol',
  'Yofre Sud',
]

export const REQUIREMENTS = [
  // ── Más pedidos (de grupos reales) ──
  { id: 'apta_credito', label: 'Apta crédito hipotecario' },
  { id: 'una_sola_planta', label: 'Una sola planta / Planta baja' },
  { id: 'con_escritura', label: 'Con escritura al día' },
  { id: 'desocupado', label: 'Desocupada / Sin inquilinos' },
  { id: 'patio', label: 'Con patio' },
  { id: 'cochera_techada', label: 'Cochera techada / Cubierta' },
  { id: 'en_pozo', label: 'En pozo / A estrenar' },
  // ── Características adicionales ──
  { id: 'pileta', label: 'Pileta' },
  { id: 'gas_natural', label: 'Gas natural' },
  { id: 'calles_asfaltadas', label: 'Calles asfaltadas' },
  { id: 'jardin', label: 'Jardín / Patio grande' },
  { id: 'sum', label: 'SUM / Amenities' },
  { id: 'luz_natural', label: 'Buena iluminación natural' },
  { id: 'cocina_amplia', label: 'Cocina amplia / Separada' },
  { id: 'living_amplio', label: 'Living / Espacio social amplio' },
  { id: 'dvh', label: 'Aberturas DVH' },
  { id: 'calefaccion_central', label: 'Calefacción central' },
  { id: 'antiguedad', label: 'Menos de 15 años de antigüedad' },
  { id: 'terraza', label: 'Terraza / Balcón' },
]

// Specific security types (replaces the generic "seguridad" requirement)
export const SEGURIDAD_TIPOS = [
  { id: 'rejas', label: 'Rejas' },
  { id: 'guardia_cuadra', label: 'Guardia en la cuadra' },
  { id: 'housing', label: 'Housing' },
  { id: 'barrio_cerrado', label: 'Barrio cerrado' },
  { id: 'country', label: 'Country' },
]

export const PRIORITY_OPTIONS = [
  { id: 'zona_exacta', label: '📍 La zona es clave, no me muevo de ahí' },
  { id: 'precio_fijo', label: '💰 El presupuesto es fijo, no me excedo' },
  { id: 'tamano', label: '📐 El tamaño (m² / dormitorios) no es negociable' },
  { id: 'sin_reformas', label: '🔑 Sin reformas, listo para entrar' },
  { id: 'nuevo', label: '✨ Quiero algo nuevo o casi nuevo (< 10 años)' },
  { id: 'disponibilidad', label: '⚡ Necesito disponibilidad inmediata' },
]

export const URGENCY_OPTIONS = [
  { id: 'esta_semana', label: 'Esta semana' },
  { id: 'este_mes', label: 'Este mes' },
  { id: 'en_3_meses', label: 'En los próximos 3 meses' },
  { id: 'flexible', label: 'Flexible, cuando aparezca lo ideal' },
]

export const CREDIT_PACKS = [
  { id: 'pack_3',         credits: 3,   price_ars: 80000,  label: '3 créditos',        price_per_ars: 26667, popular: false, unlimited: false },
  { id: 'pack_5',         credits: 5,   price_ars: 100000, label: '5 créditos',        price_per_ars: 20000, popular: true,  unlimited: false },
  { id: 'pack_10',        credits: 10,  price_ars: 180000, label: '10 créditos',       price_per_ars: 18000, popular: false, unlimited: false },
  { id: 'pack_unlimited', credits: 999, price_ars: 350000, label: 'Ilimitado mensual', price_per_ars: 0,     popular: false, unlimited: true  },
]

export const PROPERTY_TYPE_LABELS: Record<string, string> = {
  casa: 'Casa',
  departamento: 'Departamento',
  duplex: 'Dúplex',
  terreno: 'Terreno',
  local: 'Local Comercial',
  renta: 'Inversión para renta',
  revaluo: 'Inversión para revalúo',
}

export const FINANCING_LABELS: Record<string, string> = {
  efectivo: 'Efectivo / EFVO',
  credito: 'Crédito Hipotecario',
  ambos: 'Efectivo o Crédito',
}

export const CAR_BRANDS = [
  'Toyota', 'Ford', 'Volkswagen', 'Chevrolet', 'Renault', 'Peugeot',
  'Fiat', 'Honda', 'Hyundai', 'Jeep', 'Nissan', 'Kia', 'Citroën',
  'Suzuki', 'Dodge', 'Otro',
]

export const CAR_BODY_STYLES: { id: string; label: string; icon: string }[] = [
  { id: 'sedan', label: 'Sedán', icon: '🚗' },
  { id: 'suv', label: 'SUV / 4x4', icon: '🚙' },
  { id: 'hatchback', label: 'Hatchback', icon: '🚗' },
  { id: 'pickup', label: 'Pickup', icon: '🛻' },
  { id: 'monovolumen', label: 'Monovolumen', icon: '🚐' },
  { id: 'coupe', label: 'Coupé / Sport', icon: '🏎️' },
]

export const CAR_FUEL_TYPES: { id: string; label: string }[] = [
  { id: 'nafta', label: 'Nafta' },
  { id: 'diesel', label: 'Diesel' },
  { id: 'gnc', label: 'GNC' },
  { id: 'electrico', label: 'Eléctrico' },
  { id: 'hibrido', label: 'Híbrido' },
]

export const CAR_TRANSMISSION_OPTIONS = [
  { id: 'manual', label: 'Manual' },
  { id: 'automatico', label: 'Automático' },
  { id: 'cualquiera', label: 'Cualquiera' },
]

export const CAR_CONDITION_OPTIONS = [
  { id: 'nuevo', label: '✨ 0km / Nuevo' },
  { id: 'usado', label: '🔑 Usado' },
  { id: 'cualquiera', label: '🔄 Cualquiera' },
]

export const CAR_BODY_STYLE_LABELS: Record<string, string> = {
  sedan: 'Sedán',
  suv: 'SUV / 4x4',
  hatchback: 'Hatchback',
  pickup: 'Pickup',
  monovolumen: 'Monovolumen',
  coupe: 'Coupé',
}
