export const ZONAS_CORDOBA = [
  'Norte',
  'Calera',
  'Villa Allende',
  'Sur',
  'Centro / Nueva Córdoba / Gral. Paz / Güemes / Alto Alberdi',
  'Corredor Carlos Paz',
  'E53',
]

export const ZONES_CORDOBA = [
  'Acosta',
  'Alberdi',
  'Almirante Brown',
  'Alqarias',
  'Alta Córdoba',
  'Alta Gracia',
  'Alto Alberdi',
  'Alto Verde',
  'Altos de Manantiales',
  'Altos del Chateau',
  'Ameghino Norte',
  'Ameghino Sud',
  'Ampliación Empalme',
  'Ampliación Las Palmas',
  'Anisacate',
  'Argüello',
  'Argüello Norte',
  'Ascochinga',
  'Ayacucho',
  'Bajo Palermo',
  'Bell Ville',
  'Bella Vista',
  'Bicentenario',
  'Bouwer',
  'Brisas de Manantiales',
  'Cabana',
  'Campos de Manantiales',
  'Cañitas',
  'Cañuelas Country',
  'Capilla del Monte',
  'Causana',
  'Centro',
  'Cerro de las Rosas',
  'Chacras de la Villa',
  'Chateau Carreras',
  'Ciudad de los Niños',
  'Cofico',
  'Colinas de Manantiales',
  'Colinas de Vélez Sársfield',
  'Colonia Caroya',
  'Colonia Lola',
  'Comarca',
  'Condominios del Valle',
  'Cosquín',
  'Costa Azul',
  'Costas de Manantiales',
  'Country Club Jockey',
  'Crisol Norte',
  'Crisol Sur',
  'Cruz del Eje',
  'Cuatro Hojas',
  'Cuesta Colorada',
  'Cumbres',
  'Cumbres del Golf',
  'Cupani',
  'Deán Funes',
  'Docta',
  'Docta Avenida',
  'Docta Boulevard',
  'Docta Central',
  'Docta Parque',
  'Docta Soho',
  'Don Bosco',
  'Ducasse',
  'Dumesnil',
  'Duplares',
  'Ejército Argentino',
  'El Balcón',
  'El Bosque',
  'El Perchel',
  'El Prado',
  'El Talar',
  'Empalme',
  'Estación Juárez Celman',
  'Estancia Q2',
  'Ferreyra',
  'Fontanas del Sur',
  'Fortín del Pozo',
  'General Paz',
  'Golf',
  'Granja de Funes',
  'Green Park',
  'Greenville',
  'Güemes',
  'Heredades',
  'Hermitage',
  'Hipódromo',
  'Housing del Valle',
  'Inaudi',
  'Ipona',
  'Ituzaingó',
  'Jardín',
  'Jardín Claret',
  'Jardín del Pilar',
  'Jardín Espinosa',
  'Jardín Hipódromo',
  'Jesús María',
  'José Ignacio Díaz',
  'Juniors',
  'Kennedy',
  'La Calera',
  'La Carolina',
  'La Cascada',
  'La Cercanía',
  'La Cuesta',
  'La Cumbre',
  'La Cumbrecita',
  'La Deseada',
  'La Falda',
  'La Herradura',
  'La Luisita',
  'La Morada',
  'La Reserva',
  'La Rosella',
  'La Rufina',
  'La Serena',
  'Laguna Larga',
  'Las Corzuelas',
  'Las Delicias',
  'Las Margaritas',
  'Las Palmas',
  'Las Rosas',
  'Las Veras',
  'Lofts',
  'Lomas de la Carolina',
  'Lomas de Mendiolaza',
  'Lomas de Villa Allende',
  'Lomas Este',
  'Lomas Sur',
  'Los Árboles',
  'Los Aromas',
  'Los Boulevares',
  'Los Carolinos',
  'Los Cielos',
  'Los Naranjos',
  'Los Nogales',
  'Los Pinos',
  'Los Plátanos',
  'Los Reartes',
  'Los Robles',
  'Los Soles',
  'Los Sueños',
  'Los Vascos',
  'Maipú',
  'Maipú I',
  'Maipú II',
  'Malagueño',
  'Maldonado',
  'Manantiales',
  'Manantiales I',
  'Manantiales II',
  'Mansos del Sur',
  'Marcos Juárez',
  'Marqués de Sobremonte',
  'Marqués de Sobremonte Anexo',
  'Mendiolaza',
  'Mirador del Chateau',
  'Miradores de Manantiales',
  'Miralta',
  'Mitte',
  'Nobu',
  'Nueva Córdoba',
  'Nueva Italia',
  'Nuevo Urca',
  'Ñu Porá',
  'O\'Higgins',
  'Observatorio',
  'Oncativo',
  'Pacífico',
  'Parque Capital',
  'Parque Chacabuco',
  'Parque Chateau Carreras',
  'Parque Futura',
  'Parque Montecristo',
  'Parque Vélez Sársfield',
  'Parterres',
  'Paso de los Andes',
  'Patagonia Village',
  'Patricios',
  'Piedras Blancas',
  'Pilar',
  'Poblado',
  'Poeta Lugones',
  'Portón de Piedra',
  'Providencia',
  'Pueyrredón',
  'Quebrada de las Rosas',
  'Quebrada Honda',
  'Quebradas de Manantiales',
  'Quintas de Italia',
  'Quintas de San Isidro',
  'Quintas de Santa Ana',
  'Renacimiento',
  'Residencial América',
  'Residencial San Carlos',
  'Residencial Vélez Sarsfield',
  'Rincones de Manantiales',
  'Río Ceballos',
  'Río Cuarto',
  'Río Tercero',
  'Rogelio Martínez',
  'Rosedal',
  'Saldán',
  'Salsipuedes',
  'San Alfonso',
  'San Antonio',
  'San Carlos',
  'San Fernando',
  'San Francisco',
  'San Ignacio Village',
  'San Lorenzo',
  'San Martín',
  'San Remo',
  'San Vicente',
  'Santa Ana',
  'Santa Rita',
  'Santa Rosa de Calamuchita',
  'Santina Norte',
  'Santina Sur',
  'Senda',
  'SEP',
  'Sierra Nueva',
  'Siete Soles',
  'Sinsacate',
  'Sol y Río',
  'Solares de Manantiales',
  'Tablada Park',
  'Talar',
  'Talleres',
  'Tejas del Sur',
  'Terrazas de Manantiales',
  'Terrazas del Valle',
  'Tierra Alta',
  'Toledo',
  'Tropezon',
  'Unquillo',
  'Urca',
  'Valle del Sol',
  'Valle Escondido',
  'Valle Hermoso',
  'Verandas',
  'Villa Adela',
  'Villa Allende',
  'Villa Aspacia',
  'Villa Belgrano',
  'Villa Cabrera',
  'Villa Carlos Paz',
  'Villa Catalina',
  'Villa del Dique',
  'Villa del Lago',
  'Villa del Parque',
  'Villa Díaz',
  'Villa El Libertador',
  'Villa General Belgrano',
  'Villa Giardino',
  'Villa María',
  'Villa Martínez',
  'Villa Páez',
  'Villa Revol',
  'Villa Rivera Indarte',
  'Villa Warcalde',
  'Villasol',
  'Yocsina',
  'Yofre Sud',
]

export const REQUIREMENTS = [
  // ── Más pedidos (de grupos reales) ──
  { id: 'apta_credito', label: 'Apta crédito hipotecario' },
  { id: 'una_sola_planta', label: 'Una sola planta / Planta baja' },
  { id: 'con_escritura', label: 'Con escritura al día' },
  { id: 'desocupado', label: 'Desocupada / Sin inquilinos' },
  { id: 'patio', label: 'Con patio' },
  { id: 'cochera_techada', label: 'Cochera techada / Cubierta' },
  { id: 'en_pozo', label: 'En pozo / A estrenar' },
  // ── Características adicionales ──
  { id: 'pileta', label: 'Pileta' },
  { id: 'gas_natural', label: 'Gas natural' },
  { id: 'calles_asfaltadas', label: 'Calles asfaltadas' },
  { id: 'jardin', label: 'Jardín / Patio grande' },
  { id: 'sum', label: 'SUM / Amenities' },
  { id: 'luz_natural', label: 'Buena iluminación natural' },
  { id: 'cocina_amplia', label: 'Cocina amplia / Separada' },
  { id: 'living_amplio', label: 'Living / Espacio social amplio' },
  { id: 'dvh', label: 'Aberturas DVH' },
  { id: 'calefaccion_central', label: 'Calefacción central' },
  { id: 'antiguedad', label: 'Menos de 15 años de antigüedad' },
  { id: 'terraza', label: 'Terraza / Balcón' },
]

// Specific security types (replaces the generic "seguridad" requirement)
export const SEGURIDAD_TIPOS = [
  { id: 'rejas', label: 'Rejas' },
  { id: 'guardia_cuadra', label: 'Guardia en la cuadra' },
  { id: 'housing', label: 'Housing' },
  { id: 'barrio_cerrado', label: 'Barrio cerrado' },
  { id: 'country', label: 'Country' },
]

export const PRIORITY_OPTIONS = [
  { id: 'zona_exacta', label: '📍 La zona es clave, no me muevo de ahí' },
  { id: 'precio_fijo', label: '💰 El presupuesto es fijo, no me excedo' },
  { id: 'tamano', label: '📐 El tamaño (m² / dormitorios) no es negociable' },
  { id: 'sin_reformas', label: '🔑 Sin reformas, listo para entrar' },
  { id: 'nuevo', label: '✨ Quiero algo nuevo o casi nuevo (< 10 años)' },
  { id: 'disponibilidad', label: '⚡ Necesito disponibilidad inmediata' },
]

export const URGENCY_OPTIONS = [
  { id: 'esta_semana', label: 'Esta semana' },
  { id: 'este_mes', label: 'Este mes' },
  { id: 'en_3_meses', label: 'En los próximos 3 meses' },
  { id: 'flexible', label: 'Flexible, cuando aparezca lo ideal' },
]

export const CREDIT_PACKS = [
  { id: 'plan_mensual', credits: 999, price_ars: 25000, label: 'Plan mensual ilimitado', price_per_ars: 0, popular: true, unlimited: true },
]

export const PROPERTY_TYPE_LABELS: Record<string, string> = {
  casa: 'Casa',
  departamento: 'Departamento',
  duplex: 'Dúplex',
  terreno: 'Terreno',
  local: 'Local Comercial',
  renta: 'Inversión para renta',
  revaluo: 'Inversión para revalúo',
}

export const FINANCING_LABELS: Record<string, string> = {
  efectivo: 'Efectivo / EFVO',
  credito: 'Crédito Hipotecario',
  ambos: 'Efectivo o Crédito',
}

export const CAR_BRANDS = [
  'Toyota', 'Ford', 'Volkswagen', 'Chevrolet', 'Renault', 'Peugeot',
  'Fiat', 'Honda', 'Hyundai', 'Jeep', 'Nissan', 'Kia', 'Citroën',
  'Suzuki', 'Dodge', 'Otro',
]

export const CAR_BODY_STYLES: { id: string; label: string; icon: string }[] = [
  { id: 'sedan', label: 'Sedán', icon: '🚗' },
  { id: 'suv', label: 'SUV / 4x4', icon: '🚙' },
  { id: 'hatchback', label: 'Hatchback', icon: '🚗' },
  { id: 'pickup', label: 'Pickup', icon: '🛻' },
  { id: 'monovolumen', label: 'Monovolumen', icon: '🚐' },
  { id: 'coupe', label: 'Coupé / Sport', icon: '🏎️' },
]

export const CAR_FUEL_TYPES: { id: string; label: string }[] = [
  { id: 'nafta', label: 'Nafta' },
  { id: 'diesel', label: 'Diesel' },
  { id: 'gnc', label: 'GNC' },
  { id: 'electrico', label: 'Eléctrico' },
  { id: 'hibrido', label: 'Híbrido' },
]

export const CAR_TRANSMISSION_OPTIONS = [
  { id: 'manual', label: 'Manual' },
  { id: 'automatico', label: 'Automático' },
  { id: 'cualquiera', label: 'Cualquiera' },
]

export const CAR_CONDITION_OPTIONS = [
  { id: 'nuevo', label: '✨ 0km / Nuevo' },
  { id: 'usado', label: '🔑 Usado' },
  { id: 'cualquiera', label: '🔄 Cualquiera' },
]

export const CAR_BODY_STYLE_LABELS: Record<string, string> = {
  sedan: 'Sedán',
  suv: 'SUV / 4x4',
  hatchback: 'Hatchback',
  pickup: 'Pickup',
  monovolumen: 'Monovolumen',
  coupe: 'Coupé',
}
