/**
 * Seed script — inserta pedidos de WhatsApp al grupo de inmobiliarias
 * Origen: mensajes del grupo (29/5/26)
 * Ejecutar: node scripts/seed_pedidos.js
 *
 * Notas:
 *  - publisher_type = 'inmobiliaria' en todos
 *  - contact_phone = '3510000000' como placeholder cuando no se indicó
 *  - budget_usd = 0 en casos de "a convenir" o "permuta"
 */

const SUPABASE_URL = 'https://aqndahpjtkjgmwyltruy.supabase.co'
const SERVICE_ROLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxbmRhaHBqdGtqZ213eWx0cnV5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTMwMTgyMSwiZXhwIjoyMDk0ODc3ODIxfQ.AaQiiCUJyFqJ0ZSs1eUPCw5M7nixMLythzORpUB7XXg'

const PLACEHOLDER_PHONE = '3510000000'
const PLACEHOLDER_CONTACT = 'Inmobiliaria (WhatsApp grupal)'

// Todos los pedidos a insertar
const pedidos = [
  // ─── DEPARTAMENTOS - CENTRO / NUEVA CÓRDOBA / GENERAL PAZ ───────────────────

  {
    property_types: ['departamento'],
    zones: ['Centro'],
    budget_usd: 45000,
    bedrooms_min: 1, bedrooms_max: 1,
    financing: 'ambos',
    description: 'Puede estar con renta / alquilado.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba'],
    budget_usd: 75000,
    bedrooms_min: 1, bedrooms_max: 1,
    financing: 'ambos',
    description: 'Preferentemente desocupado o con pronta desocupación.',
    requirements: ['desocupado'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['General Paz'],
    budget_usd: 65000,
    financing: 'ambos',
    description: 'Preferentemente con balcón externo, buena luz, ventilación y distribución. Edificio bien mantenido, buena administración, expensas razonables. Cercano a plaza Alberdi. Producto con buena salida para alquiler y potencial de reventa futura.',
    contact_name: 'Giesenow Servicios Inmobiliarios',
    contact_phone: '3512124925',
    agency_name: 'Giesenow Servicios Inmobiliarios',
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba'],
    budget_usd: 110000,
    bedrooms_min: 2, bedrooms_max: 2,
    financing: 'credito',
    description: 'Con balcón. Apto crédito Banco Nación. Tienen 30 días para elegir la propiedad.',
    requirements: ['apta_credito'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba'],
    budget_usd: 80000,
    financing: 'efectivo',
    description: 'Busco departamento en oportunidad en Nueva Córdoba para hacer flipping (revalorización). Se analizan opciones para comprar esta semana. Presupuesto flexible según la oportunidad.',
    urgency: 'esta_semana',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba', 'General Paz'],
    budget_usd: 130000,
    bedrooms_min: 1, bedrooms_max: 1,
    financing: 'ambos',
    description: 'Búsqueda con vista a los Capuchinos. Zona Nueva Córdoba o General Paz.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba'],
    budget_usd: 120000,
    bedrooms_min: 1, bedrooms_max: 2,
    financing: 'efectivo',
    description: '1 dormitorio amplio con opción a 2 dormitorios o 1 dorm + escritorio. Frente con balcón. Cocina separada. Edificio en buen estado de conservación (no muy antiguo). Cochera en el edificio o cercana. NO sobre Vélez Sarsfield, NO sobre Tránsito Cáceres, NO calle Rondeau. Prioridad: ubicación y estado del edificio.',
    requirements: ['cochera_techada'],
    contact_name: 'Mariana Macario - LiCASA',
    contact_phone: PLACEHOLDER_PHONE,
    agency_name: 'LiCASA',
  },
  {
    property_types: ['departamento'],
    zones: ['General Paz'],
    budget_usd: 65000,
    bedrooms_min: 1, bedrooms_max: 1,
    financing: 'efectivo',
    description: 'Departamento moderno para inversión. Con escritura.',
    requirements: ['con_escritura'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba'],
    budget_usd: 0,
    bedrooms_min: 2, bedrooms_max: 3,
    financing: 'efectivo',
    description: 'Cliente busca departamento de 2 o 3 dormitorios en Nueva Córdoba. Operación de permuta: tiene Dúplex en Manantiales para entregar como parte de pago.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['General Paz'],
    budget_usd: 45000,
    bedrooms_min: 0, bedrooms_max: 0,
    financing: 'efectivo',
    description: 'Monoambiente. Cliente super filtrado con documentación en orden.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba', 'General Paz'],
    budget_usd: 120000,
    bedrooms_min: 1, bedrooms_max: 2,
    financing: 'ambos',
    description: 'Con escritura. Antigüedad no más de 12 años. Mínimo 70 m2. Se evalúa 1 dorm amplio o 1 dorm + espacio de escritorio si el depto es grande.',
    requirements: ['con_escritura', 'antiguedad'],
    contact_name: 'Carolina Fiore CPI 4759',
    contact_phone: PLACEHOLDER_PHONE,
    agency_name: 'Carolina Fiore CPI 4759',
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba'],
    budget_usd: 85000,
    bedrooms_min: 1, bedrooms_max: 1,
    financing: 'ambos',
    description: 'Con balcón, amplio. Puede estar alquilado (con inquilino).',
    contact_name: 'Chiara Peretti',
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba', 'General Paz'],
    budget_usd: 80000,
    bedrooms_min: 1, bedrooms_max: 1,
    financing: 'ambos',
    description: 'Departamento usado. Destino: renta / inversión.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['General Paz'],
    budget_usd: 85000,
    bedrooms_min: 2, bedrooms_max: 2,
    financing: 'efectivo',
    description: 'Plata en mano. Operación rápida.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['General Paz', 'Cofico', 'Alta Córdoba'],
    budget_usd: 75000,
    bedrooms_min: 1, bedrooms_max: 1,
    financing: 'efectivo',
    description: 'Balcón amplio o patio. Antigüedad hasta 5 años aprox. Posesión inmediata. Búsqueda firme.',
    requirements: ['desocupado'],
    urgency: 'este_mes',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['General Paz'],
    budget_usd: 65000,
    bedrooms_min: 1, bedrooms_max: 1,
    financing: 'ambos',
    description: 'Pedido puntual de 1 dormitorio en General Paz.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Cofico', 'Centro', 'General Paz'],
    budget_usd: 90000,
    bedrooms_min: 2, bedrooms_max: 2,
    financing: 'ambos',
    description: 'Zona linda. Que tenga buena renta para alquiler.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba'],
    budget_usd: 120000,
    bedrooms_min: 1, bedrooms_max: 2,
    financing: 'credito',
    description: 'Frente con balcón. Con escritura y plano municipal actualizado para crédito Banco Nación.',
    requirements: ['con_escritura', 'apta_credito'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba'],
    budget_usd: 250000,
    bedrooms_min: 2, bedrooms_max: 3,
    financing: 'efectivo',
    description: 'Con cochera. Antigüedad hasta 10 años. Operación de contado. Zona calles Estrada o Irigoyen.',
    requirements: ['cochera_techada', 'con_escritura'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba'],
    budget_usd: 160000,
    bedrooms_min: 2, bedrooms_max: 2,
    financing: 'ambos',
    description: 'Zona Poeta Lugones, con vista al parque. Para inversión.',
    contact_name: 'Ornella Carole - Burni Inversiones',
    contact_phone: PLACEHOLDER_PHONE,
    agency_name: 'Burni Inversiones',
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba', 'General Paz'],
    budget_usd: 130000,
    bedrooms_min: 1, bedrooms_max: 2,
    financing: 'ambos',
    description: 'Hasta 30 años de antigüedad. Cochera excluyente.',
    requirements: ['cochera_techada'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba', 'Centro'],
    budget_usd: 80000,
    bedrooms_min: 2, bedrooms_max: 2,
    financing: 'ambos',
    description: 'Pedido concreto de 2 dormitorios en Nueva Córdoba o Centro.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba'],
    budget_usd: 85000,
    bedrooms_min: 1, bedrooms_max: 1,
    financing: 'efectivo',
    description: 'Zona preferida: Buen Pastor, Salguero o cercano a Bv. Illia. Con balcón. Menos de 10 años de antigüedad o refaccionado. Cash.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba'],
    budget_usd: 69000,
    bedrooms_min: 1, bedrooms_max: 1,
    financing: 'credito',
    description: 'Apto crédito hipotecario. Excluyente.',
    requirements: ['apta_credito', 'con_escritura'],
    contact_name: 'Carolina Fiore CPI 4759',
    contact_phone: PLACEHOLDER_PHONE,
    agency_name: 'Carolina Fiore CPI 4759',
  },
  {
    property_types: ['departamento'],
    zones: ['General Paz', 'Cofico'],
    budget_usd: 72000,
    bedrooms_min: 1, bedrooms_max: 1,
    financing: 'credito',
    description: 'Apto crédito hipotecario. Excluyente.',
    requirements: ['apta_credito', 'con_escritura'],
    contact_name: 'Carolina Fiore CPI 4759',
    contact_phone: PLACEHOLDER_PHONE,
    agency_name: 'Carolina Fiore CPI 4759',
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba'],
    budget_usd: 125000,
    bedrooms_min: 1, bedrooms_max: 1,
    financing: 'credito',
    description: 'Frente con balcón. Apto crédito hipotecario. Búsqueda urgente.',
    requirements: ['apta_credito'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento', 'casa'],
    zones: ['General Paz', 'Nueva Córdoba', 'Centro', 'Argüello'],
    budget_usd: 125000,
    bedrooms_min: 2, bedrooms_max: 2,
    financing: 'credito',
    description: 'Casa planta baja o departamento. Apto crédito francés. Se evalúa zona norte también.',
    requirements: ['apta_credito', 'una_sola_planta'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba', 'Centro'],
    budget_usd: 47000,
    financing: 'ambos',
    description: 'Búsqueda de departamento en Nueva Córdoba o Centro.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['General Paz'],
    budget_usd: 95000,
    bedrooms_min: 1, bedrooms_max: 1,
    financing: 'ambos',
    description: 'Con balcón frente (no primer piso, preferiblemente pisos bajos). Con escritura. Sin amenities. Antigüedad máxima 15 años. Desocupado.',
    requirements: ['con_escritura', 'desocupado', 'antiguedad'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },

  // ─── CASAS - ZONA CENTRO/SUR ─────────────────────────────────────────────────

  {
    property_types: ['casa'],
    zones: ['General Paz', 'Juniors', 'Cofico', 'Alta Córdoba'],
    budget_usd: 115000,
    bedrooms_min: 3, bedrooms_max: 3,
    financing: 'ambos',
    description: 'Casa no muy antigua. Búsqueda urgente.',
    urgency: 'esta_semana',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa', 'departamento'],
    zones: ['Yofre Sud'],
    budget_usd: 90000,
    bedrooms_min: 3, bedrooms_max: 3,
    financing: 'credito',
    description: 'Zona Barrio Capdevila, Yofre o Márquez, con salida rápida a circunvalación. Con cochera. 1 baño. Apta crédito.',
    requirements: ['apta_credito', 'cochera_techada'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa', 'duplex'],
    zones: ['Residencial Vélez Sarsfield', 'Jardín', 'San Fernando'],
    budget_usd: 100000,
    bedrooms_min: 2, bedrooms_max: 3,
    financing: 'credito',
    description: 'Búsqueda URGENTE. Apta crédito Banco Nación con planos actualizados. Zona sur: Residencial Vélez Sarsfield, Parque VS, Parque Horizonte, Parque Atlántica, Barrio Jardín, San Fernando y similares.',
    requirements: ['apta_credito', 'con_escritura'],
    urgency: 'esta_semana',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa', 'duplex'],
    zones: ['Residencial Vélez Sarsfield', 'Jardín', 'San Fernando'],
    budget_usd: 80000,
    bedrooms_min: 2, bedrooms_max: 3,
    financing: 'credito',
    description: 'Zona sur. Apta crédito Banco Nación. Otra interesada para el mismo tipo de búsqueda.',
    requirements: ['apta_credito', 'con_escritura'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa'],
    zones: ['Alta Córdoba', 'Ayacucho', 'Villa Cabrera'],
    budget_usd: 125000,
    bedrooms_min: 2, bedrooms_max: 3,
    financing: 'efectivo',
    description: 'Casa planta baja. Zona Lomas de San Martín, Alta Córdoba, Villa Cabrera, Ayacucho. Efectivo.',
    requirements: ['una_sola_planta'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa'],
    zones: ['Urca'],
    budget_usd: 185000,
    bedrooms_min: 3, bedrooms_max: 3,
    financing: 'efectivo',
    description: 'CRITERIOS EXCLUYENTES: barrio Urca, una sola planta, patio con pileta (o posibilidad de hacerla), cochera para 2 autos. Efectivo. Cliente con venta de otra propiedad avanzada.',
    requirements: ['una_sola_planta', 'patio', 'pileta', 'cochera_techada'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },

  // ─── DEPARTAMENTOS / CASAS - ZONA NORTE ─────────────────────────────────────

  {
    property_types: ['departamento'],
    zones: ['Argüello', 'Villa Belgrano', 'Cerro de las Rosas'],
    budget_usd: 120000,
    bedrooms_min: 1, bedrooms_max: 2,
    financing: 'ambos',
    description: 'Búsqueda de departamento en zona norte.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['duplex'],
    zones: ['Villa Belgrano', 'Argüello'],
    budget_usd: 250000,
    financing: 'efectivo',
    description: 'Sin pileta. Dentro de housing. Expensas bajas o sin expensas. Cliente con dinero en mano.',
    requirements: ['housing'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa'],
    zones: ['Argüello Norte', 'Villa Belgrano', 'Cerro de las Rosas'],
    budget_usd: 320000,
    bedrooms_min: 3, bedrooms_max: 3,
    financing: 'efectivo',
    description: 'Barrio cerrado. Vista a las sierras. Mucho verde. 3 dormitorios y 3 baños. Contado.',
    requirements: ['barrio_cerrado'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa', 'duplex'],
    zones: ['Alto Verde', 'Urca', 'Cerro de las Rosas', 'Tablada Park', 'Villa Rivera Indarte', 'Argüello'],
    budget_usd: 140000,
    bedrooms_min: 3, bedrooms_max: 3,
    financing: 'credito',
    description: 'Casa o dúplex con patio. Escritura y planos actualizados. Apto crédito.',
    requirements: ['apta_credito', 'con_escritura', 'patio'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa'],
    zones: ['Poeta Lugones', 'Marqués de Sobremonte'],
    budget_usd: 140000,
    bedrooms_min: 3, bedrooms_max: 3,
    financing: 'ambos',
    description: 'Con escritura. 3 dormitorios, 2 baños.',
    requirements: ['con_escritura'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Argüello', 'Villa Belgrano'],
    budget_usd: 240000,
    financing: 'ambos',
    description: 'Buen espacio de guardado. Buenas terminaciones.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa'],
    zones: ['Villa Belgrano'],
    budget_usd: 0,
    bedrooms_min: 3, bedrooms_max: 3,
    financing: 'efectivo',
    description: 'Housing en Villa Belgrano con escritura. Operación rápida de contado efectivo. Presupuesto a negociar.',
    requirements: ['housing', 'con_escritura'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa', 'duplex'],
    zones: ['Argüello', 'Villa Belgrano', 'Cerro de las Rosas'],
    budget_usd: 150000,
    bedrooms_min: 3, bedrooms_max: 3,
    financing: 'efectivo',
    description: 'Con seguridad. Sin crédito. (Alternativa: hasta USD 200.000 si es apta crédito.)',
    requirements: ['housing'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa', 'duplex'],
    zones: ['Valle Escondido', 'Villa Warcalde', 'Villa Belgrano'],
    budget_usd: 350000,
    bedrooms_min: 3, bedrooms_max: 3,
    financing: 'efectivo',
    description: 'Casa o duplex moderno en zona norte. Con seguridad. Contado.',
    requirements: ['barrio_cerrado'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Nueva Córdoba', 'General Paz'],
    budget_usd: 100000,
    bedrooms_min: 2, bedrooms_max: 2,
    financing: 'efectivo',
    description: 'Con balcón, pileta, amenities. Vacío. Si es complejo cerrado mejor. Contado.',
    requirements: ['pileta', 'sum'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa'],
    zones: ['Tablada Park', 'Argüello'],
    budget_usd: 180000,
    bedrooms_min: 3, bedrooms_max: 3,
    financing: 'credito',
    description: 'Crédito Banco Nación ya aprobado. Urgencia de compra. Zona norte abierto (Villa Marta, Villa Centenario, Alejandro Centeno, Tablada Park). Garage para 2 vehículos. Patio.',
    requirements: ['apta_credito', 'cochera_techada', 'patio'],
    urgency: 'este_mes',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa', 'duplex'],
    zones: ['Villa Catalina', 'Valle Escondido'],
    budget_usd: 100000,
    bedrooms_min: 2, bedrooms_max: 3,
    financing: 'efectivo',
    description: 'Housing o barrio cerrado. Se evalúa Villa Catalina, Valle Escondido y similares.',
    requirements: ['housing'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa', 'duplex'],
    zones: ['Mendiolaza', 'Unquillo', 'Valle Escondido', 'Villa Belgrano'],
    budget_usd: 230000,
    bedrooms_min: 2, bedrooms_max: 3,
    financing: 'efectivo',
    description: 'Barrio con seguridad. Cochera cubierta. No más de 10 años de antigüedad. Gas natural (al menos en el barrio). Calles asfaltadas. 2 o 3 dormitorios, 2 baños (puede ser 1 baño + toilette). Cliente REITERA búsqueda.',
    requirements: ['housing', 'cochera_techada', 'gas_natural', 'calles_asfaltadas', 'antiguedad'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Poeta Lugones', 'Argüello'],
    budget_usd: 150000,
    bedrooms_min: 1, bedrooms_max: 2,
    financing: 'ambos',
    description: 'Departamento en housing o edificio en zona Poeta Lugones o zona norte. Con escritura.',
    requirements: ['con_escritura'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa', 'duplex'],
    zones: ['Argüello', 'Villa Belgrano', 'Tablada Park'],
    budget_usd: 180000,
    bedrooms_min: 3, bedrooms_max: 3,
    financing: 'credito',
    description: 'Apto crédito. Cochera cubierta para 2 autos. Patio y jardín. Luminosa y moderna. Zona: Alejandro Centeno, Santa Marta, Alto Verde, Villa Centenario o similar.',
    requirements: ['apta_credito', 'cochera_techada', 'patio', 'jardin'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa', 'duplex'],
    zones: ['Observatorio', 'Nueva Córdoba'],
    budget_usd: 90000,
    bedrooms_min: 2, bedrooms_max: 2,
    financing: 'credito',
    description: 'Zona Ciudad Universitaria. Crédito Banco Nación. Cochera x 2. Patio.',
    requirements: ['apta_credito', 'cochera_techada', 'patio'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['departamento'],
    zones: ['Argüello', 'General Paz', 'Cofico'],
    budget_usd: 160000,
    bedrooms_min: 2, bedrooms_max: 2,
    financing: 'ambos',
    description: 'Dos dormitorios, dos baños. Preferentemente habitación en suite con vestidor. Con cochera.',
    requirements: ['cochera_techada'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['duplex'],
    zones: ['Docta', 'Argüello'],
    budget_usd: 90000,
    financing: 'credito',
    description: 'Duplex apto crédito. Se evalúan opciones en Docta o cualquier barrio de zona norte.',
    requirements: ['apta_credito', 'con_escritura'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['duplex'],
    zones: ['Docta'],
    budget_usd: 130000,
    bedrooms_min: 2, bedrooms_max: 3,
    financing: 'efectivo',
    description: 'Duplex en Docta. Posesión inmediata. Pago contado.',
    urgency: 'esta_semana',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa', 'duplex'],
    zones: ['Argüello', 'Cerro de las Rosas'],
    budget_usd: 145000,
    bedrooms_min: 2, bedrooms_max: 2,
    financing: 'credito',
    description: 'Tipo housing de 2 dormitorios. Apto crédito Banco Nación.',
    requirements: ['apta_credito', 'housing', 'con_escritura'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa'],
    zones: ['Cerro de las Rosas'],
    budget_usd: 180000,
    financing: 'ambos',
    description: 'Casa en venta en Cerro de las Rosas y alrededores.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa'],
    zones: ['Argüello', 'Villa Belgrano', 'Cerro de las Rosas', 'Tablada Park'],
    budget_usd: 210000,
    bedrooms_min: 2, bedrooms_max: 3,
    financing: 'ambos',
    description: 'Casa con terreno mayor a 400 m2. Zona Argüello, Villa Belgrano, Cerro, Tablada Park.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa'],
    zones: ['Docta'],
    budget_usd: 152000,
    bedrooms_min: 3, bedrooms_max: 3,
    financing: 'ambos',
    description: 'Casa terminada en Docta. Zona con gas natural. Calefacción central. Vidrios DVH.',
    requirements: ['gas_natural', 'calefaccion_central', 'dvh'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa'],
    zones: ['Valle Escondido', 'Mendiolaza', 'Unquillo'],
    budget_usd: 400000,
    bedrooms_min: 2, bedrooms_max: 3,
    financing: 'efectivo',
    description: 'Casa en zona intercountry. Preferentemente toda en planta baja (no excluyente). Fácil acceso y sin muchos desniveles.',
    requirements: ['una_sola_planta'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['duplex'],
    zones: ['Manantiales I'],
    budget_usd: 160000,
    financing: 'credito',
    description: 'Dúplex en Manantiales I. Apto crédito.',
    requirements: ['apta_credito', 'con_escritura'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa'],
    zones: ['Manantiales II'],
    budget_usd: 250000,
    bedrooms_min: 3, bedrooms_max: 3,
    financing: 'ambos',
    description: 'Casa planta baja en Manantiales II.',
    requirements: ['una_sola_planta'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['duplex'],
    zones: ['Manantiales II'],
    budget_usd: 160000,
    bedrooms_min: 2, bedrooms_max: 2,
    financing: 'ambos',
    description: 'Dúplex 2 dormitorios en planta baja en Manantiales II.',
    requirements: ['una_sola_planta'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['casa', 'duplex'],
    zones: ['Argüello', 'Villa Belgrano'],
    budget_usd: 130000,
    bedrooms_min: 2, bedrooms_max: 3,
    financing: 'credito',
    description: 'Apto crédito (ya aprobado). 2 o 3 cuartos.',
    requirements: ['apta_credito', 'con_escritura'],
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },

  // ─── TERRENOS / LOTES ────────────────────────────────────────────────────────

  {
    property_types: ['terreno'],
    zones: ['Docta'],
    budget_usd: 35000,
    financing: 'efectivo',
    description: 'Lote en Docta para inversión. Contado.',
    contact_name: 'Nicolas Bello',
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['terreno'],
    zones: ['Manantiales I', 'Manantiales II'],
    budget_usd: 60000,
    financing: 'efectivo',
    description: 'Lote en Pampas de Manantiales o Abras de Manantiales. Apto duplex.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['terreno'],
    zones: ['Campos de Manantiales'],
    budget_usd: 54000,
    financing: 'efectivo',
    description: 'Lote en Campos de Manantiales. Apto duplex.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['terreno'],
    zones: ['Rincones de Manantiales', 'Quebradas de Manantiales', 'Brisas de Manantiales'],
    budget_usd: 0,
    financing: 'efectivo',
    description: 'Lote en Rincones, Quebradas o Brisas de Manantiales. Apto duplex. Presupuesto a convenir.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
  {
    property_types: ['terreno'],
    zones: ['Altos de Manantiales'],
    budget_usd: 0,
    financing: 'efectivo',
    description: 'Lote en Riberas, Lomas o Altos de Manantiales. Presupuesto a convenir.',
    contact_name: PLACEHOLDER_CONTACT,
    contact_phone: PLACEHOLDER_PHONE,
  },
]

// ─── INSERCIÓN ────────────────────────────────────────────────────────────────

async function insertPedidos() {
  console.log(`\nInsertando ${pedidos.length} pedidos...\n`)
  let ok = 0
  let fail = 0

  for (let i = 0; i < pedidos.length; i++) {
    const p = pedidos[i]

    const body = {
      request_type: 'property',
      property_types: p.property_types,
      zones: p.zones,
      budget_usd: p.budget_usd,
      bedrooms_min: p.bedrooms_min ?? null,
      bedrooms_max: p.bedrooms_max ?? null,
      financing: p.financing,
      requirements: p.requirements ?? [],
      description: p.description ?? null,
      urgency: p.urgency ?? null,
      contact_name: p.contact_name,
      contact_phone: p.contact_phone,
      contact_email: p.contact_email ?? null,
      status: 'active',
      publisher_type: 'inmobiliaria',
      agency_name: p.agency_name ?? null,
      buyer_user_id: null,
    }

    const res = await fetch(`${SUPABASE_URL}/rest/v1/buyer_requests`, {
      method: 'POST',
      headers: {
        'apikey': SERVICE_ROLE_KEY,
        'Authorization': `Bearer ${SERVICE_ROLE_KEY}`,
        'Content-Type': 'application/json',
        'Prefer': 'return=minimal',
      },
      body: JSON.stringify(body),
    })

    if (res.ok) {
      ok++
      const zone = p.zones[0]
      const type = p.property_types[0]
      const budget = p.budget_usd > 0 ? `USD ${p.budget_usd.toLocaleString()}` : 'a convenir'
      console.log(`  ✓ [${i+1}/${pedidos.length}] ${type} en ${zone} - ${budget}`)
    } else {
      fail++
      const text = await res.text()
      console.error(`  ✗ [${i+1}/${pedidos.length}] ERROR: ${res.status} — ${text.substring(0, 200)}`)
      console.error(`    Datos: ${JSON.stringify(body).substring(0, 300)}`)
    }
  }

  console.log(`\n─────────────────────────────`)
  console.log(`Resultado: ${ok} insertados, ${fail} errores`)
}

insertPedidos().catch(console.error)
